"""Single-qubit Clifford group for Randomized Benchmarking.

The single-qubit Clifford group has 24 elements. Each is represented as a
list of gate names (from {h, s, x, z}) that can be applied to a Marqov Circuit.

The group is closed under composition and every element has an inverse,
enabling the RB protocol: apply a random sequence of Cliffords, then apply
the inverse of the composed sequence to return to |0>.

References:
    Gambetta et al. 2012, arXiv:1204.6308
"""

from __future__ import annotations

import math
import random as stdlib_random

import numpy as np

from marqov.circuits import Circuit

# Gate matrices
_I = np.eye(2, dtype=complex)
_H = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
_S = np.array([[1, 0], [0, 1j]], dtype=complex)
_X = np.array([[0, 1], [1, 0]], dtype=complex)
_Z = np.array([[1, 0], [0, -1]], dtype=complex)

_GATE_MATRICES = {"h": _H, "s": _S, "x": _X, "z": _Z}

# The 24 single-qubit Cliffords, each as a list of gate names.
# Generated by exhaustive composition of H and S (which generate the group),
# with X and Z for convenience. Element 0 is identity.
CLIFFORD_GROUP: list[list[str]] = [
    [],                                 # 0: I
    ["h"],                              # 1: H
    ["s"],                              # 2: S
    ["h", "s"],                         # 3: HS
    ["s", "h"],                         # 4: SH
    ["s", "s"],                         # 5: S^2 = Z
    ["h", "s", "h"],                    # 6: HSH
    ["h", "s", "s"],                    # 7: HS^2
    ["s", "h", "s"],                    # 8: SHS
    ["s", "s", "h"],                    # 9: S^2 H
    ["s", "s", "s"],                    # 10: S^3 = Sdg
    ["h", "s", "h", "s"],              # 11: HSHS
    ["h", "s", "s", "h"],              # 12: HS^2 H
    ["h", "s", "s", "s"],              # 13: HS^3
    ["s", "h", "s", "s"],              # 14: SHS^2
    ["s", "s", "h", "s"],              # 15: S^2 HS
    ["h", "s", "h", "s", "s"],         # 16: HSHS^2
    ["h", "s", "s", "h", "s"],         # 17: HS^2 HS
    ["s", "h", "s", "s", "h"],         # 18: SHS^2 H
    ["s", "h", "s", "s", "s"],         # 19: SHS^3
    ["s", "s", "h", "s", "s"],         # 20: S^2 HS^2
    ["h", "s", "h", "s", "s", "h"],    # 21: HSHS^2 H
    ["h", "s", "h", "s", "s", "s"],    # 22: HSHS^3
    ["h", "s", "s", "h", "s", "s"],    # 23: HS^2 HS^2
]

# Precomputed tables (populated by _init_tables on import)
_CLIFFORD_MATRICES: list[np.ndarray] = []
_COMPOSE_TABLE: list[list[int]] = []
_INVERSE_TABLE: list[int] = []


def _gates_to_matrix(gates: list[str]) -> np.ndarray:
    """Convert a gate sequence to a 2x2 unitary matrix."""
    mat = _I.copy()
    for gate in gates:
        mat = _GATE_MATRICES[gate] @ mat
    return mat


def _matrices_equal_up_to_phase(a: np.ndarray, b: np.ndarray) -> bool:
    """Check if two 2x2 unitaries are equal up to global phase."""
    product = a @ b.conj().T
    # If equal up to phase, product = e^{i*theta} * I
    if abs(product[0, 1]) > 1e-10 or abs(product[1, 0]) > 1e-10:
        return False
    if abs(abs(product[0, 0]) - 1.0) > 1e-10:
        return False
    # Both diagonal entries must be the same phase
    return bool(abs(product[0, 0] - product[1, 1]) < 1e-10)


def _find_clifford(mat: np.ndarray) -> int:
    """Find which Clifford index matches a given matrix (up to global phase)."""
    for i, ref in enumerate(_CLIFFORD_MATRICES):
        if _matrices_equal_up_to_phase(mat, ref):
            return i
    raise ValueError("Matrix does not match any Clifford")


def _init_tables() -> None:
    """Precompute composition and inverse lookup tables."""
    global _CLIFFORD_MATRICES, _COMPOSE_TABLE, _INVERSE_TABLE

    _CLIFFORD_MATRICES.clear()
    for gates in CLIFFORD_GROUP:
        _CLIFFORD_MATRICES.append(_gates_to_matrix(gates))

    # Verify all 24 are distinct
    for i in range(24):
        for j in range(i + 1, 24):
            if _matrices_equal_up_to_phase(
                _CLIFFORD_MATRICES[i], _CLIFFORD_MATRICES[j]
            ):
                raise ValueError(
                    f"Clifford {i} and {j} are the same up to global phase"
                )

    # Composition: compose(i, j) = k where U_k = U_j @ U_i (j applied after i)
    _COMPOSE_TABLE.clear()
    for i in range(24):
        row = []
        for j in range(24):
            product = _CLIFFORD_MATRICES[j] @ _CLIFFORD_MATRICES[i]
            k = _find_clifford(product)
            row.append(k)
        _COMPOSE_TABLE.append(row)

    _INVERSE_TABLE.clear()
    for i in range(24):
        inv_mat = _CLIFFORD_MATRICES[i].conj().T
        _INVERSE_TABLE.append(_find_clifford(inv_mat))


_init_tables()


def clifford_to_matrix(index: int) -> np.ndarray:
    """Get the 2x2 unitary matrix for a Clifford element."""
    return _CLIFFORD_MATRICES[index].copy()


def compose_clifford_indices(i: int, j: int) -> int:
    """Compose two Cliffords: result = j applied after i."""
    return _COMPOSE_TABLE[i][j]


def inverse_clifford_index(i: int) -> int:
    """Get the inverse Clifford index."""
    return _INVERSE_TABLE[i]


def generate_rb_sequence(
    length: int,
    seed: int | None = None,
    max_retries: int = 3,
) -> list[int]:
    """Generate a random RB sequence of Clifford indices.

    Returns length + 1 indices: ``length`` random Cliffords followed by
    the inverse of their composition, so the full sequence composes to identity.

    Samples from elements 1-23 (excluding identity) to ensure every Clifford
    contributes at least one physical gate. If the final sequence would produce
    an empty circuit (pathological cancellation), re-rolls with a different seed.

    Args:
        length: Number of random Cliffords (not counting the inverse).
        seed: Random seed for reproducibility.
        max_retries: Maximum re-roll attempts if circuit would be empty.

    Returns:
        List of Clifford indices of length ``length + 1``.
    """
    for attempt in range(max_retries + 1):
        current_seed = seed + attempt * 7919 if seed is not None else None
        rng = stdlib_random.Random(current_seed)

        # Sample from 1-23 (exclude identity element 0)
        sequence = [rng.randrange(1, 24) for _ in range(length)]

        composed = 0  # identity
        for idx in sequence:
            composed = compose_clifford_indices(composed, idx)

        inverse = inverse_clifford_index(composed)
        sequence.append(inverse)

        # Check that the sequence produces at least one gate
        total_gates = sum(len(CLIFFORD_GROUP[idx]) for idx in sequence)
        if total_gates > 0:
            return sequence

        if attempt < max_retries:
            import logging
            logging.getLogger(__name__).info(
                "RB sequence (length=%d, seed=%s) produced zero gates, re-rolling (attempt %d)",
                length, seed, attempt + 1,
            )

    # Exhausted retries — return the sequence anyway (failure isolation will catch it)
    return sequence


def clifford_to_circuit(sequence: list[int], qubit: int) -> Circuit:
    """Convert a Clifford index sequence to a Marqov Circuit on a specific qubit."""
    circuit = Circuit()
    for idx in sequence:
        for gate in CLIFFORD_GROUP[idx]:
            getattr(circuit, gate)(qubit)
    return circuit


# Native gate decompositions for Rigetti (Rx, Rz only):
# H = Rz(π) · Rx(π/2)   (up to global phase)
# S = Rz(π/2)
# X = Rx(π)
# Z = Rz(π)
_NATIVE_GATE_MAP: dict[str, list[tuple[str, float]]] = {
    "h": [("rz", math.pi), ("rx", math.pi / 2)],
    "s": [("rz", math.pi / 2)],
    "x": [("rx", math.pi)],
    "z": [("rz", math.pi)],
}


def clifford_to_circuit_native(sequence: list[int], qubit: int) -> Circuit:
    """Convert a Clifford index sequence to a Circuit using only Rx/Rz gates.

    Required for Rigetti verbatim compilation — native gate set only inside
    verbatim blocks. Produces the same unitary as clifford_to_circuit() but
    decomposed into Rx(θ) and Rz(θ) rotations.

    Args:
        sequence: List of Clifford group indices.
        qubit: Physical qubit index.

    Returns:
        Circuit using only Rx and Rz gates.
    """
    circuit = Circuit()
    for idx in sequence:
        for gate in CLIFFORD_GROUP[idx]:
            for native_gate, angle in _NATIVE_GATE_MAP[gate]:
                getattr(circuit, native_gate)(angle, qubit)
    return circuit
